AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: finiancial-tracker-api-lambda-function
Resources:
  FinanceAppLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A lambda function that processes financial data
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: FinancialAppDB
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
  FinancialAppDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: financial-app-db
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
